//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoaderTraker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Users {
            get {
                return ((string)(this["Users"]));
            }
            set {
                this["Users"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CompanyName {
            get {
                return ((string)(this["CompanyName"]));
            }
            set {
                this["CompanyName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Address1 {
            get {
                return ((string)(this["Address1"]));
            }
            set {
                this["Address1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Address2 {
            get {
                return ((string)(this["Address2"]));
            }
            set {
                this["Address2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"ALU CARTER 2% FER
ALU JANTES
MOTEUR ALU/ FONTE ALU
ALU PROFILE MELE
ALU LAMINE 1% FER ALE MELE
CUIVRE MELE
CUIVRE MILBERRY
CUIVRE ETAME
CUIVRE CHAUFFE EAU
CABLE ALU MELE 40%
FERAILLES
VF1 (DISQUES)
VF2 (FONTE)
CABLES CUIVRE PAUVRE
CABLES CUIVRE RICHE
ZINC
PLOMB
BATTERIES
METAUX FERREUX
CABLES CUIVRE MELE
LAITON MELE
CABLES Cu/Pb/Fe
INOX 18/8
MOTEURS ELECTRIQUES
ALU NEUF BLANC
ALU ALMELEC
ALU PROFILE BLANC
ALU TOURNURES
INOX F17")]
        public string Products {
            get {
                return ((string)(this["Products"]));
            }
            set {
                this["Products"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SalesHistory {
            get {
                return ((string)(this["SalesHistory"]));
            }
            set {
                this["SalesHistory"] = value;
            }
        }
    }
}
